services:
  edge-infer:
    build:
      context: ./EdgeInfer
      dockerfile: Dockerfile
    container_name: edge-infer
    init: true
    user: "1000:1000"
    ports:
      - "8080:8080"
    volumes:
      - /opt/hailo:/opt/hailo:ro
    environment:
      LOG_LEVEL: info
      PORT: 8080
    restart: unless-stopped
    stop_grace_period: 20s
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:8080/healthz >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 800M
        reservations:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    image: vapor-app:latest
    container_name: vapor
    user: "1000:1000"
    ports:
      - "8082:8080"
    volumes:
      - /home/pi/appdata/sessions:/var/app/sessions
    environment:
      LOG_LEVEL: info
      SESSIONS_DIR: /var/app/sessions
    restart: unless-stopped
    depends_on:
      edge-infer:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/healthz || exit 1"]
      interval: 30s
      timeout: 2s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

