groups:
- name: pisrv_api_rules
  interval: 30s
  rules:
  - alert: PiSrvHighErrorRate
    expr: |
      (
        sum(rate(http_requests_total{status=~"5..|4.."}[5m]))
      / sum(rate(http_requests_total[5m]))
      ) > 0.05
    for: 5m
    labels:
      severity: warning
      service: pisrv
    annotations:
      summary: "High API error rate (>5% for 5m)"
      description: "Current 4xx/5xx ratio is above 5% over 5 minutes."

  - alert: PiSrvLatencyP95High
    expr: |
      histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m]))) > 0.5
    for: 10m
    labels:
      severity: warning
      service: pisrv
    annotations:
      summary: "High API latency p95 (>0.5s for 10m)"
      description: "95th percentile latency across routes exceeded 500ms for 10 minutes."

  - alert: PiSrvNoTraffic
    expr: sum(rate(http_requests_total[10m])) == 0
    for: 15m
    labels:
      severity: info
      service: pisrv
    annotations:
      summary: "No incoming traffic"
      description: "No HTTP requests received in the last 10 minutes."
