name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift: [ "5.10", "6.0", "6.1" ]
        include:
          - swift: "6.1"
            experimental: true
    container:
      image: swift:${{ matrix.swift }}-jammy
    continue-on-error: ${{ matrix.experimental || false }}
    steps:
      - uses: actions/checkout@v4

      - name: Show Swift version
        run: swift --version

      - name: Resolve
        run: swift package resolve

      - name: Test (discovery)
        run: swift test -v --enable-test-discovery --jobs 2

      - name: Summary
        if: always()
        run: |
          if [ "${{ matrix.experimental || false }}" = "true" ]; then
            echo "🐤 Swift ${{ matrix.swift }} canary CI complete (experimental)"
          else
            echo "Swift ${{ matrix.swift }} CI complete"
          fi
